import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import IntroVideo from "./components/IntroVideo";
import CursorRing from "./components/CursorRing";
import Navbar from "./components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}`}>
      
      <body>
        <IntroVideo />
        <Navbar />

        <main>
          {children}
        </main>
        
      </body>
    </html>
  );
}